[package]
name = "minigl"
version = "0.1.0"
authors = ["viri <git@stuff.moe>"]
edition = "2018"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3", features = ["libloaderapi"] }
